nilfs2: use kthread_run() instead of kernel_thread()
kernel_thread() was taken over by kthread_run(), and its use
is discouraged in recent kernels.
This makes that replacement, and fixes the following error reported by
scripts/checkpatch.pl,

 ERROR: Don't use kernel_thread(): see
 Documentation/feature-removal-schedule.txt
 #3368: FILE: segment.c:3368:
 +       kernel_thread(nilfs_segctor_thread, sci,

Signed-off-by: Ryusuke Konishi <konishi.ryusuke@lab.ntt.co.jp>